repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: b8b6637a9c7e27a7354de9f4f846ce3b6e746f5f
    hooks:
      - id: pre-commit-update
        args: [--config-file, pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c
    hooks:
      - id: trailing-whitespace
        exclude: ^examples/
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: ^examples/
      - id: check-added-large-files
        exclude: ^examples/
      - id: check-merge-conflict
        exclude: ^examples/
      - id: debug-statements
        exclude: ^examples/
      - id: check-toml
        exclude: ^examples/
      - id: check-json
        exclude: ^examples/
      - id: check-case-conflict
        exclude: ^examples/
      - id: mixed-line-ending
        exclude: ^examples/

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7
    hooks:
      - id: yamllint
        args: [-c, .yamllint]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.json]
        files: \.(md|markdown)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 455f64b32459518aa82ec33b63f799ed048d65a9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [types-toml, types-PyYAML, pytest,
                                  types-setuptools]
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 2d0b675b04c80ae42277e10500db06a0a37bae17
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: fb5a27193ad89e24d37319409d242dfd43a235dd
    hooks:
      - id: uv-lock

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 78f5e0f104cfa803d0597eaa924b4de3becd3e3e
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: ^(docs/|examples/|htmlcov/)
