name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yaml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yaml"

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install documentation dependencies
        run: uv sync --group docs

      - name: Update docs version from pyproject.toml
        run: |
          import tomllib
          import re

          # Read version from pyproject.toml
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
              version = data['project']['version']

          # Update docs/conf.py
          with open('docs/conf.py', 'r') as f:
              content = f.read()

          # Replace the release line
          updated_content = re.sub(
              r'^release = "[^"]*"',
              f'release = "{version}"',
              content,
              flags=re.MULTILINE
          )

          with open('docs/conf.py', 'w') as f:
              f.write(updated_content)

          print(f"Updated docs version to {version}")
        shell: python

      - name: Build documentation
        run: |
          mkdir -p docs/_static
          uv run sphinx-build -b html docs docs/_build/html --keep-going

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: documentation
          path: docs/_build/html/
          retention-days: 30
